services:
  app: 
    image: prom/prometheus:latest
    container_name: prometheus_app
    hostname: prometheus_app
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.globaldomain`)"
      - "traefik.http.routers.prometheus.entrypoints=web"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"      
    networks:
      - traefik-net
    volumes:
      - /volumes/prometheus:/etc/prometheus
      - /volumes/prometheus/data:/prometheus
    restart: unless-stopped

networks:
  traefik-net:
    driver: bridge
    external: true     
